- name: kamiflora
  hosts: localhost
  gather_facts: no
  connection: local
  become: true
  become_method: sudo
  #debugger: always
      
  tasks:
    - name: "Install python lib with pip"
      pip:
       name: "{{ item }}"
      loop:
       - ephem
       - google_trans_new

    - name: "Install python lib with apt"
      apt:
       name: "{{ item }}"
      loop:
       - bluetooth
       - bluez

    - name: "Install miflora daemon"
      ansible.builtin.git:
       repo: https://github.com/ThomDietrich/miflora-mqtt-daemon.git
       dest: /opt/miflora-mqtt-daemon

    - name: "Install requirements.txt"
      pip:
       requirements: /opt/miflora-mqtt-daemon/requirements.txt

    - name: "merge files in json folders"
      ansible.builtin.command:
        cmd: python3 merge_json_folders.py













        
     
    

