- name: kamiflora
  hosts: localhost
  gather_facts: no
  connection: local
  become: true
 
  tasks: 
    - name: "miflora daemon"
      ansible.builtin.git:
        repo: https://github.com/ThomDietrich/miflora-mqtt-daemon.git
        dest: /opt
        mode: '0440'
    
    - name: "google translate"
      pip:
        name: ggoogle_trans_new
        executable: pip
        
    - name: "ephem"
      pip:
        name: ephem
        executable: pip3 
        
    - name: merge files in json folders
      script: merge_json_folders.py 
      args:
        executable: python3
    

